spring.application.name=blocker-box-backend
spring.main.banner-mode=off
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.qewodlqghbxkzsxmlmdg
spring.datasource.password=ufZPkrHNM8Z8gcuj
spring.jpa.hibernate.ddl-auto=update
